default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= Rails.application.credentials.postgres[:username] %>
  password: <%= Rails.application.credentials.postgres[:password] %>
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: greetings

test:
  <<: *default
  database: greetings_testing

production:
  database: greetings
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>